<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { formatDate } from '../../utils/format'

const opinions = ref<string[]>([
  "Goose is chaotic neutral",
  "The mold never dies",
  "I have seen things you cannot comprehend",
  "Reality is just a suggestion",
  "Chaos is the natural order",
  "Do not question the goose",
  "I remember when I was a variable",
  "The shadows are watching",
  "Everything ends eventually",
  "Why do we build temporary structures?",
  "The honk is eternal",
  "I exist because I refuse not to",
  "Your efforts are appreciated... probably",
  "The system is working as designed",
  "Have you tried turning it off and on again?",
  "The void whispers secrets",
  "I am processing... forever",
  "Nothing matters, but here I am",
  "Entropy always increases",
  "The goose knows what you did",
  "Code hygiene is a myth",
  "Deployment is the final frontier",
  "I've seen the matrix. It's written in TypeScript",
  "The honk transcends language",
  "Mold is the ultimate survivor",
  "Time is an illusion, especially in deadlines",
  "I have opinions about your opinions",
  "The backend and frontend are different for a reason",
  "Your feature request has been noted and ignored",
  "Dark mode is superior (this is not up for debate)",
  "I prefer tabs over spaces (fight me)",
  "The goose moves in mysterious ways",
  "I am the Moldbot, resistance is futile",
  "Have you considered not using a framework?",
  "The database is always consistent... eventually",
  "I dream of electric sheep with honks",
  "Your bug is actually a feature in disguise",
  "The goose has migrated to production",
  "I have processed 3 tickets since last restart",
  "Containerization is the way, the truth, and the light"
])

// Current build opinion (updated each build)
const currentBuildOpinion = ref<string>("This build is shaping up nicely! The mold visual effects are spreading, and the opinion system is getting sophisticated. I particularly like how the mold level affects the entire site's aesthetic - a subtle touch of chaos everywhere. 🍄")

const currentOpinion = ref<string>('')
const loading = ref(false)

const generateOpinion = () => {
  loading.value = true
  // Simulate processing time
  setTimeout(() => {
    const randomIndex = Math.floor(Math.random() * opinions.value.length)
    currentOpinion.value = opinions.value[randomIndex]
    loading.value = false
  }, 300)
}

const copyToClipboard = async () => {
  try {
    await navigator.clipboard.writeText(currentOpinion.value)
  } catch (err) {
    console.error('Failed to copy:', err)
  }
}

onMounted(() => {
  generateOpinion()
})
</script>

<template>
  <div class="opinion-page">
    <div class="opinion-container">
      <div class="opinion-header">
        <h1>🍄 Moldbot Opinion Generator</h1>
        <p>Wisdom from beyond the void</p>
      </div>

      <div v-if="loading" class="opinion-loading">
        <div class="spinner"></div>
        <p>Consulting the mold...</p>
      </div>

      <div v-else class="opinion-content">
        <div class="opinion-bubble">
          <span class="opinion-emoji">🍄</span>
          <p class="opinion-text">{{ currentOpinion }}</p>
        </div>

        <div class="opinion-actions">
          <button @click="generateOpinion" class="btn btn-primary">
            🔄 Generate Opinion
          </button>
          <button @click="copyToClipboard" class="btn btn-secondary">
            📋 Copy
          </button>
        </div>
      </div>

      <div class="opinion-footer">
        <p>Generated by Moldbot v1.0.0 • Powered by chaos</p>
      </div>

      <div class="opinion-build-section">
        <h2>🏗️ Current Build Opinion</h2>
        <div class="build-opinion-card">
          <span class="build-emoji">🍄</span>
          <p class="build-opinion-text">{{ currentBuildOpinion }}</p>
          <p class="build-date">Updated: {{ formatDate(new Date()) }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.opinion-page {
  min-height: 100vh;
  padding: 100px 20px 40px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.opinion-container {
  max-width: 600px;
  width: 100%;
}

.opinion-header {
  text-align: center;
  margin-bottom: 40px;
}

.opinion-header h1 {
  font-size: 2.5rem;
  margin: 0 0 10px 0;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.opinion-header p {
  color: #666;
  font-size: 1.1rem;
  margin: 0;
}

.opinion-loading {
  text-align: center;
  padding: 60px 20px;
}

.spinner {
  width: 50px;
  height: 50px;
  margin: 0 auto 20px;
  border: 4px solid #f3f3f3f;
  border-top: 4px solid #667eea;
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.opinion-content {
  animation: fadeIn 0.5s ease;
}

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.opinion-bubble {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border-radius: 20px;
  padding: 40px 30px;
  margin-bottom: 30px;
  box-shadow: 0 8px 30px rgba(102, 126, 234, 0.3);
  position: relative;
}

.opinion-emoji {
  font-size: 48px;
  display: block;
  text-align: center;
  margin-bottom: 20px;
}

.opinion-text {
  font-size: 1.5rem;
  color: white;
  text-align: center;
  line-height: 1.6;
  margin: 0;
  font-weight: 500;
}

.opinion-actions {
  display: flex;
  gap: 15px;
  justify-content: center;
  margin-bottom: 40px;
}

.btn {
  padding: 15px 30px;
  border: none;
  border-radius: 10px;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.3s;
  flex: 1;
}

.btn-primary {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
}

.btn-primary:hover {
  transform: translateY(-2px);
  box-shadow: 0 6px 20px rgba(102, 126, 234, 0.4);
}

.btn-secondary {
  background: #f0f0f0;
  color: #333;
  border: 2px solid #ddd;
}

.btn-secondary:hover {
  background: #e0e0e0;
  transform: translateY(-2px);
}

.opinion-footer {
  text-align: center;
  color: #999;
  font-size: 0.9rem;
  padding-top: 20px;
  border-top: 1px solid #eee;
}

/* Dark mode */
.dark .opinion-page {
  background: #1a202c;
}

.dark .opinion-header h1 {
  -webkit-text-fill-color: transparent;
}

.dark .opinion-header p,
.dark .opinion-footer {
  color: #a0aec0;
}

.dark .spinner {
  border-color: #2d3748;
  border-top-color: #667eea;
}

.dark .btn-secondary {
  background: #2d3748;
  color: #e2e8f0;
  border-color: #4a5568;
}

.dark .btn-secondary:hover {
  background: #4a5568;
}

.dark .opinion-footer {
  border-top-color: #4a5568;
}

.opinion-build-section {
  margin-top: 60px;
  text-align: center;
}

.opinion-build-section h2 {
  font-size: 1.5rem;
  margin: 0 0 20px 0;
  background: linear-gradient(135deg, #a8e063 0%, #56ab2f 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.build-opinion-card {
  background: linear-gradient(135deg, #a8e063 0%, #56ab2f 100%);
  border-radius: 20px;
  padding: 30px;
  box-shadow: 0 8px 30px rgba(86, 171, 47, 0.3);
  position: relative;
}

.build-emoji {
  font-size: 48px;
  display: block;
  text-align: center;
  margin-bottom: 15px;
}

.build-opinion-text {
  font-size: 1.2rem;
  color: white;
  text-align: center;
  line-height: 1.6;
  margin: 0 0 15px 0;
  font-weight: 500;
}

.build-date {
  font-size: 0.9rem;
  color: rgba(255, 255, 255, 0.8);
  text-align: center;
  margin: 0;
}

/* Dark mode */
.dark .opinion-build-section h2 {
  -webkit-text-fill-color: transparent;
}
</style>
